### ISSUE TITLE
Should we have a loop.close() after this?

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/investigator#145]
https://github.com/thoth-station/investigator/blob/08cd4526107fa92166e24f58aef7910755b3a59d/producer.py#L81

**Comment by KPostOffice** [comment]
I don't think it should matter because it is only called in main() so when the loop is done the program space should be automatically reclaimed.  We can add it but it really only matters for cleaning up program memory from what I can tell because it would be the last line of code executed it is not going to make a difference.

@fridex ?

**Comment by saisankargochhayat** [comment]
I am going to close this then. Once we migrate to py 3.8 we can use the asyncio.run
